# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design/hiroko.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtWidgets
import pyqtgraph as pg


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 600)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 650))
        MainWindow.setMaximumSize(QtCore.QSize(1200, 650))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(20, 10, 441, 111))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.epoch_seek = QtWidgets.QCheckBox(self.groupBox)
        self.epoch_seek.setGeometry(QtCore.QRect(20, 32, 111, 22))
        self.epoch_seek.setObjectName("epoch_seek")
        self.start_btn = QtWidgets.QPushButton(self.groupBox)
        self.start_btn.setGeometry(QtCore.QRect(20, 65, 88, 34))
        self.start_btn.setObjectName("start_btn")
        self.previous_btn = QtWidgets.QPushButton(self.groupBox)
        self.previous_btn.setGeometry(QtCore.QRect(130, 65, 51, 34))
        self.previous_btn.setObjectName("previous_btn")
        self.next_btn = QtWidgets.QPushButton(self.groupBox)
        self.next_btn.setGeometry(QtCore.QRect(190, 65, 51, 34))
        self.next_btn.setObjectName("next_btn")
        self.day_count = QtWidgets.QSpinBox(self.groupBox)
        self.day_count.setGeometry(QtCore.QRect(130, 30, 111, 32))
        self.day_count.setReadOnly(False)
        self.day_count.setMinimum(10)
        self.day_count.setMaximum(20)
        self.day_count.setProperty("value", 10)
        self.day_count.setObjectName("day_count")
        self.deviation = QtWidgets.QLabel(self.groupBox)
        self.deviation.setGeometry(QtCore.QRect(260, 58, 171, 18))
        self.deviation.setObjectName("deviation")
        self.distance = QtWidgets.QLabel(self.groupBox)
        self.distance.setGeometry(QtCore.QRect(260, 38, 171, 18))
        self.distance.setObjectName("distance")
        self.fitness = QtWidgets.QLabel(self.groupBox)
        self.fitness.setGeometry(QtCore.QRect(260, 78, 171, 18))
        self.fitness.setObjectName("fitness")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(19, 129, 441, 491))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setGeometry(QtCore.QRect(479, 9, 701, 301))
        self.groupBox_3.setTitle("")
        self.groupBox_3.setObjectName("groupBox_3")
        self.scatter_plot = pg.PlotWidget(self.groupBox_3)
        self.scatter_plot.setGeometry(QtCore.QRect(0, 9, 701, 292))
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_4.setGeometry(QtCore.QRect(479, 309, 701, 291))
        self.groupBox_4.setTitle("")
        self.groupBox_4.setObjectName("groupBox_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 30))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuNew = QtWidgets.QMenu(self.menuFile)
        self.menuNew.setObjectName("menuNew")
        self.menuSettings = QtWidgets.QMenu(self.menubar)
        self.menuSettings.setObjectName("menuSettings")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGenetic = QtWidgets.QAction(MainWindow)
        self.actionGenetic.setObjectName("actionGenetic")
        self.actionRandom = QtWidgets.QAction(MainWindow)
        self.actionRandom.setObjectName("actionRandom")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionModify = QtWidgets.QAction(MainWindow)
        self.actionModify.setObjectName("actionModify")
        self.actionImport_Rule_Book = QtWidgets.QAction(MainWindow)
        self.actionImport_Rule_Book.setObjectName("actionImport_Rule_Book")
        self.menuNew.addAction(self.actionGenetic)
        self.menuNew.addAction(self.actionRandom)
        self.menuFile.addAction(self.menuNew.menuAction())
        self.menuFile.addAction(self.actionOpen)
        self.menuSettings.addAction(self.actionModify)
        self.menuSettings.addAction(self.actionImport_Rule_Book)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Hiroko Minimal Interface"))
        self.epoch_seek.setText(_translate("MainWindow", "Seek epochs"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.previous_btn.setText(_translate("MainWindow", "Prev"))
        self.next_btn.setText(_translate("MainWindow", "Next"))
        self.deviation.setText(_translate("MainWindow", "Best Deviation:"))
        self.distance.setText(_translate("MainWindow", "Best Distance:"))
        self.fitness.setText(_translate("MainWindow", "Fitness Value:"))
        self.menuFile.setTitle(_translate("MainWindow", "Fi&le"))
        self.menuNew.setTitle(_translate("MainWindow", "New"))
        self.menuSettings.setTitle(_translate("MainWindow", "&Settings"))
        self.actionGenetic.setText(_translate("MainWindow", "Genetic"))
        self.actionRandom.setText(_translate("MainWindow", "Random"))
        self.actionOpen.setText(_translate("MainWindow", "Load dump File"))
        self.actionModify.setText(_translate("MainWindow", "Modify"))
        self.actionImport_Rule_Book.setText(_translate("MainWindow", "Import Rule Book"))
